{% set version = "0.10" %}

package:
  name: create-forwarder-dll
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/create-forwarder-dll/create_forwarder_dll-{{ version }}.tar.gz
  sha256: 57b316492486e31d9d4160ddb5e44511335195d696310896aada34a0dc19d7ec

build:
  entry_points:
    - create-forwarder-dll = create_forwarder_dll:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=8.1
    - pip
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - create_forwarder_dll
  commands:
    - pip check
    - create-forwarder-dll --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/isuruf/create-forwarder-dll
  summary: Creates a DLL that forwards all the symbols to another DLL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
